### ISSUE TITLE
Account field value clean up

### ISSUE THREAD

**Issue by kaittodesk** [sendsmaily/Sendsmaily-Sync-for-Magento#1]
Admin configuration field "Sendsmaily account" does not clean up inserted value. For example, user can insert `https://xxx.sendsmaily.net`, which actually does not work.

It should either validate the value and throw an error, try to make an API request to that account or parse subdomain from given value.

**Comment by sendsmaily** [comment]
Fixed the issue (for now) by parsing subdomain from inserted value. For example it can detect the account from `https://xxx.sendsmaily.net` and `xxx.sendsmaily.net` values.
